services:
  newisms-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NEO4J_URI=neo4j://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - GEMINI_API_KEY=AIzaSyD5JGQI54cH3K7gDrPOK55I7zKd0ldEcW8
    volumes:
      - ./newisms-server:/app/newisms-server
    depends_on:
      - neo4j

  neo4j:
    image: neo4j:5.15-community
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - ../data/neo4j:/data
      - ../data/neo4j-logs:/logs